all:
	gcc main.c header.h ft_putstr.c cpu_easy.c check_game_over.c user_compute_map.c ft_putchar.c move_to_array.c ft_atoi.c l_add_node.c l_init_list.c print_board.c read_file.c validate_line.c messages.c start_game.c get_user_decision.c validate_user_input.c get_next_line/*.c get_next_line/libft/*.c
